import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getActiveInventory } from "./lib/vehicles/repository";
import { VehicleProvider } from "./lib/vehicles/vehicle-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const vehicles = await getActiveInventory();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <VehicleProvider initialVehicles={vehicles}>{children}</VehicleProvider>
      </body>
    </html>
  );
}
