import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getActiveInventory } from "./lib/vehicles/repository";
import { VehicleProvider } from "./lib/vehicles/vehicle-context";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const vehicles = await getActiveInventory();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-dvh flex flex-col overflow-hidden">
        <VehicleProvider initialVehicles={vehicles}>
          <Header />
          <main className="flex-1 overflow-y-auto">{children}</main>
          <Footer />
        </VehicleProvider>
      </body>
    </html>
  );
}
